### ISSUE TITLE
False positive error trigger when using sentry in streamlit

### ISSUE THREAD

**Issue by RHDZMOTA** [stonebase-mx/python-packages.stonebase.mx#56]
The following error is triggered when forcing a reload of a streamlit page:

```text
RuntimeError: generator didn't stop
```

Full error:

```text
2024-03-09 23:40:17,975 [ERROR] asyncio: Exception in callback _HandlerDelegate.execute.<locals>.<lambda>(<Task finishe...didn't stop")>) at /home/rhdzmota/Documents/Github/rhdzmota/package.rhdzmota.com/venv/lib/python3.10/site-packages/tornado/web.py:2438
handle: <Handle _HandlerDelegate.execute.<locals>.<lambda>(<Task finishe...didn't stop")>) at /home/rhdzmota/Documents/Github/rhdzmota/package.rhdzmota.com/venv/lib/python3.10/site-packages/tornado/web.py:2438>
Traceback (most recent call last):
  File "/home/rhdzmota/.pyenv/versions/3.10.12/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/rhdzmota/Documents/Github/rhdzmota/package.rhdzmota.com/venv/lib/python3.10/site-packages/tornado/web.py", line 2438, in <lambda>
    fut.add_done_callback(lambda f: f.result())
  File "/home/rhdzmota/Documents/Github/rhdzmota/package.rhdzmota.com/venv/lib/python3.10/site-packages/sentry_sdk/integrations/tornado.py", line 75, in sentry_execute_request_handler
    with _handle_request_impl(self):
  File "/home/rhdzmota/.pyenv/versions/3.10.12/lib/python3.10/contextlib.py", line 146, in __exit__
    raise RuntimeError("generator didn't stop")
``` 

Here's the reference to the streamlit tornado implementation: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/tornado.py 

And here is reference to a streamlit-dev conversation about this same issue. Apparently stopping to use cache_data may solve the problem temporarily... but the root-cause of the problem is not clear.
https://discuss.streamlit.io/t/runtimeerror-generator-didnt-stop/44675

**Comment by RHDZMOTA** [comment]
## Is this issue solved?

This issue seems to be resolved by changing streamlit page-config code from the dataclass `__post_init__` into the context manager (i.e., `__enter__`). 

I'll keep the issue open for some time to monitor if the issue has really been resolved.

----
## Context

We changed the streamlit page config from the `__post_init__` into `__enter__` to allow creating page instances without trigger the page-config setup (which can only be executed once, so initializing several classes resulted in a configuration error).
